---
version: '3.8'

services:
  aws_quota_exporter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 10100:10100
    volumes:
      - ./docker/aws_quota_exporter/config.yml:/etc/aqe/config.yml
      - ${AWS_FOLDER}:/exporter/.aws/
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
    command: --log.level=debug --log.format=text

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/rules:/etc/prometheus/rules

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
