# https://taskfile.dev

version: "3"

tasks:
  start:
    cmds:
      - export AWS_PROFILE=emeka;go run . --prom.port=10100 --config.file=config.yml.test --log.level=debug --log.format=text
    silent: true
  retest:
    cmds:
      - goreleaser release --snapshot --clean
    silent: true
  fuzz:
    cmds:
      - go test -fuzz=.
    silent: true
  test_verbose:
    cmds:
      - go test -v ./...
    silent: true
  test:
    cmds:
      - go test ./...
    silent: true
  compose-up:
    cmds:
      - task: compose-build
      - docker-compose up -d
  compose-down:
    cmds:
      - docker-compose down
  compose-build:
    cmds:
      - docker-compose build
  create-secret:
    cmds:
      - kubectl create secret generic aws-secrets --from-env-file=env.out
  k8-up:
    cmds:
      - kubectl apply -f kubernetes/aws_quota_exporter.yaml
      - kubectl apply -f kubernetes/prometheus.yaml
      - kubectl apply -f kubernetes/grafana.yaml
  k8-down:
    cmds:
      - kubectl delete -f kubernetes/aws_quota_exporter.yaml
      - kubectl delete -f kubernetes/prometheus.yaml
      - kubectl delete -f kubernetes/grafana.yaml
  k8-grafana:
    cmds:
      - minikube service grafana
