# https://taskfile.dev

version: "3"

tasks:
  start:
    cmds:
      - export AWS_PROFILE=emeka;go run . --prom.port=10100 --config.file=config.yml.test --log.level=debug --log.format=text
    silent: true
  retest:
    cmds:
      - goreleaser release --snapshot --clean
    silent: true
  fuzz:
    cmds:
      - go test -fuzz=.
    silent: true
  test:
    cmds:
      - go test -v ./...
    silent: true
