# https://taskfile.dev

version: "3"

includes:
  k8:
    taskfile: ./kubernetes/manifests
  helm:
    taskfile: ./kubernetes/helm
    vars:
      VERSION: 0.0.0

tasks:
  start:
    desc: "start application in dev mode"
    cmds:
      - export AWS_PROFILE=emeka;go run . --prom.port=10100 --config.file=config.yml.test --log.level=debug --log.format=text
    silent: true
  retest:
    desc: "go release build test"
    cmds:
      - goreleaser release --snapshot --clean
    silent: true
  fuzz:
    desc: "go fuzz test"
    cmds:
      - go test -fuzz=.
    silent: true
  test_verbose:
    desc: "run tests in verbose mode"
    cmds:
      - go test -v ./...
    silent: true
  test:
    desc: "run tests"
    cmds:
      - go test ./...
    silent: true
  compose-up:
    desc: "docker compose up"
    cmds:
      - task: compose-build
      - docker-compose up -d
  compose-down:
    desc: "docker compose down"
    cmds:
      - docker-compose down
  compose-build:
    desc: "build docker compose images"
    cmds:
      - docker-compose build
  docker-build:
    desc: "build docker image"
    cmds:
      - |
        commit=$(git log --format="%H" -n 1)
        docker build --build-arg="APP_VERSION=dev" --build-arg="APP_COMMIT=${commit}" -t ugwuanyi/aqe:dev -f docker/Dockerfile .
