apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aqe.fullname" . }}
  labels:
    {{- include "aqe.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secret }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
