{{- if and .Values.secret (and (.Values.secret.AWS_ACCESS_KEY_ID) (.Values.secret.AWS_SECRET_ACCESS_KEY)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aqe.fullname" . }}
  labels:
    {{- include "aqe.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secret }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
