{
 "title": "Quotas",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cloudformation module limit per account",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (aws_quota_cloudformation_module_limit_per_account)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudformation Stack count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (aws_quota_cloudformation_stack_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lambda Execution concurrency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (aws_quota_lambda_concurrent_executions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lambda Function & Layer Storage Limit",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (aws_quota_lambda_function_and_layer_storage)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}