{
 "title": "Quotas & Usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(region)" } }
  ]
 },
 "panels": [
  { "title": "Quota & Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lambda Execution concurrency (US-EAST-2)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_quota_lambda_concurrent_executions{region=\"us-east-2\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Lambda Execution concurrency (US-WEST-2)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_quota_lambda_concurrent_executions{region=\"us-west-2\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Running On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances Quota & Usage",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "repeat": "region",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_quota_ec2_running_on_demand_instances{name=\"Running On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances\", type=\"usage\", region=\"$region\"}",
     "legendFormat": "{{region}}-{{type}}"
    },
    {
     "expr": "aws_quota_ec2_running_on_demand_instances{name=\"Running On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances\", type=\"quota\", region=\"$region\"}",
     "legendFormat": "{{region}}-{{type}}"
    }
   ]
  },
  { "title": "Quotas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cloudformation module limit per account",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (aws_quota_cloudformation_module_limit_per_account)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudformation Stack count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (aws_quota_cloudformation_stacks{name=\"Stacks\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lambda Function & Layer Storage Limit",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (aws_quota_lambda_function_and_layer_storage)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}