# https://taskfile.dev

version: "3"

vars:
  VERSION: '{{.VERSION | default "0.0.0"}}'

tasks:
  up:
    desc: "package and deploy helm chart"
    cmds:
      - helm package kubernetes/helm/aqe -d packages/ --version {{.VERSION}}
      - helm install -f values.test aqe packages/aqe-{{.VERSION}}.tgz
    silent: true
  remote:
    desc: "install using remote chart"
    cmds:
      - helm repo update aws_quota_exporter
      - helm install -n aqe -f values.test aqe aws_quota_exporter/aqe
  status:
    desc: helm status
    cmds:
      - helm status aqe
  down:
    desc: delete helm chart
    cmds:
      - helm uninstall aqe
  expose-ingress:
    desc: expose minikube ingress. it is exposed by default in 127.0.0.1
    cmds:
      - minikube tunnel
  port-forward:
    desc: port forward to aqe service to port 10100 in localhost
    cmds:
      - kubectl -n default port-forward svc/aqe 10100:10100
