# https://taskfile.dev

version: "3"

vars:
  VERSION: '{{.VERSION | default "0.0.0"}}'

tasks:
  up:
    desc: "package and deploy helm chart"
    cmds:
      - helm dependency update kubernetes/helm/aqe
      - helm package kubernetes/helm/aqe -d packages/ --version {{.VERSION}}
      - helm install -f values.test aqe packages/aqe-{{.VERSION}}.tgz
    silent: true
  remote:
    desc: "install using remote chart"
    cmds:
      - helm repo update aws_quota_exporter
      - helm install -n aqe -f values.test aqe aws_quota_exporter/aqe
  status:
    desc: helm status
    cmds:
      - helm status aqe
  down:
    desc: delete helm chart
    cmds:
      - helm uninstall aqe
  expose-ingress:
    desc: expose minikube ingress. it is exposed by default in 127.0.0.1
    cmds:
      - minikube tunnel
  port-forward-aqe:
    desc: port forward to aqe services localhost
    cmds:
      - kubectl -n default port-forward svc/aqe 10100:10100 &
      - kubectl -n default port-forward svc/aqe-grafana 3000:80 &
      - kubectl -n default port-forward svc/aqe-prometheus-server 9090:80 &
  grafana-secret:
    desc: get grafana secret
    cmds:
      - kubectl get secrets aqe-grafana -o jsonpath="{.data}" | jq -r 'to_entries[] | "\(.key)=\(.value | @base64d)"'
