name: file-changes

on:
  pull_request:
    branches: ["main"]

jobs:
  detect-file-changes:
    name: detect file changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: file-changes-1
      #   run: git --no-pager diff --name-only --diff-filter=ACMRT ${{github.event.pull_request.base.sha}} ${{ github.event.pull_request.head.sha }}
      - name: file-changes-2
        run: git --no-pager diff --name-only --diff-filter=ACMRT ${{github.event.pull_request.base.sha}} ${{github.sha}}
      - name: file-changes-3
        run: git log -m -1 --name-only --pretty="format:" ${{ github.sha }}
